### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by TheBrokenWasp** [Souhardya/UBoat#10]
How the fuck do you set this up the wiki has different files 👎

**Comment by eterna2000** [comment]
why i got error 403 forbidden ?

**Comment by Souhardya** [comment]
Did y'all try url.com/path/login -> ' login '

**Comment by eterna2000** [comment]
if i try  url.com/path/login and root root get this 
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\PHP\vendor\model.php:10 Stack trace: #0

**Comment by TheBrokenWasp** [comment]
there is no fucking login page only in the views folder in private, and it's fucking blank

**Comment by eterna2000** [comment]
s2 but this is a shittest control panel ever i see

**Comment by marcoSdsu** [comment]
I change using my url panel in gate.h but I reciver eror try build biner.
Can help me?

**Comment by TheBrokenWasp** [comment]
OMFG MAKE YOUR OWN ISSUES DONT STEAL MY POST FUCKING FAGGOTS

**Comment by TheBrokenWasp** [comment]
NO I HAVE A DIFFERENT PROBLEM GET THE FUCK OUT OF MY POST SO HE CAN HELP ME, MAKE YOUR OWN FUCKING POST

**Comment by Souhardya** [comment]
High possibility there is an issue with your configuration can you please paste down your config ? Here

**Comment by TheBrokenWasp** [comment]
<?php

return [
    'base_url' => 'http://localhost/PHP/', // Base URL including trailing slash (e.g. http://localhost/)
    'default_controller' => 'main', // Default controller to load
    'encoding' => 'utf-8',
    'error_controller' => 'error', // Controller used for errors (e.g. 404, 500 etc)
    'error_type' => [
        //default 404
        '403' => 'error403',
        '404' => 'error404',
    ],
    'db' => [
        'username' => 'root',
        'password' => 'lolzmemez',
        'host' => 'localhost',
        'dbname' => 'test2'
    ],
    //screenshot settings
    'screenshots'=>[
        'enabled' => 'true',
        'external_address' => 'hidden', // 'domain_goes_here', localhost for local testing only
        'port' => '80',
    ],
    //capcha settings
    'capcha' => [
        'random_color' => 'true',
        'char_pool' => '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
        'angle' => ['-30', '30'],
        'fonts' =>['Roboto-Medium.ttf', 'Roboto-Italic.ttf'],
        'font_size' => ['10.0', '11.0'],
    ],
    //key for logs encryption
    'key' => 'root',
    //this can be turned off,
    'display_login_error' => 'true',

    // Include assets config
    'assets' => 'assets.php',


];

**Comment by Souhardya** [comment]
Okay first it should be
' test.php ' just copy and paste the generated hash in your SQL table containing user credentials to login

**Comment by TheBrokenWasp** [comment]
I already did that, I just misspelled test.php here... NONE OF THE OTHER FILES SHOWCASED IN THE WIKI EXIST, AND THE FILES THAT DO EXIST DON'T WORK... omfg I'm starting to think you didn't make this if you don't understand a simple fucking problem

**Comment by TheBrokenWasp** [comment]
Are you serious? You still won't fucking listen, I don't get an error, I get a blank screen, and here's what i get when I go to PHP/login:
[![Screenshot from Gyazo](https://gyazo.com/5a00fa5e9c5dd50fa4e175b19051ad69/raw)](https://gyazo.com/5a00fa5e9c5dd50fa4e175b19051ad69)

**Comment by TheBrokenWasp** [comment]
ok so I just calmed down and looked at your video, you seem to have the same files, but how the fuck do you go to login, I get that it wasn't found... I'm so confused

**Comment by eterna2000** [comment]
for me now control panel works 100% 
when i use test.php

**Comment by Souhardya** [comment]
@TheBrokenWasp  calm down for a min let's sort it out with cool brain

**Comment by Souhardya** [comment]
I got your point already so no need to get heated on that

**Comment by TheBrokenWasp** [comment]
ok sorry

I'm on CentOS and I just realised I'm on php 7.2.9... I'm trying to downgrade to php 7.0

**Comment by Souhardya** [comment]
Cool i am here for like 4-5 hours now so no need to sweat lemme know if the problem persists

**Comment by TheBrokenWasp** [comment]
[![Screenshot from Gyazo](https://gyazo.com/29450a3337a0aa17531a9c4cf04521bf/raw)](https://gyazo.com/29450a3337a0aa17531a9c4cf04521bf)

**Comment by Souhardya** [comment]
Are you sure that you have setup the database correctly ?

**Comment by TheBrokenWasp** [comment]
[![Screenshot from Gyazo](https://gyazo.com/574f913a36a33a249ae3de91410ace2a/raw)](https://gyazo.com/574f913a36a33a249ae3de91410ace2a)

**Comment by Souhardya** [comment]
Does visiting localhost/PHP/ also throws a 404 ?

**Comment by TheBrokenWasp** [comment]
I' not hosting localhost I'm using a VPS but no, just a blank screen

**Comment by Souhardya** [comment]
Try changing the localhost to your server ip for a min can you in the config file ? and let me know ? 
@Tuhinshubhra will be taking a look further on it

**Comment by Souhardya** [comment]
Reproduced indeed this is a bug

**Comment by Tuhinshubhra** [comment]
Downgrade to php5 and lemme know if the problem exists

**Comment by TheBrokenWasp** [comment]
PHP 5? seriously? no even the wifi says php 7.0 I JUST went through a downgrade, and let me tell you, it's not easy on CentOS... fucking yum....

**Comment by Souhardya** [comment]
I will be doing that right away

**Comment by TheBrokenWasp** [comment]
-_-

**Comment by TheBrokenWasp** [comment]
did you seriously say "minor" pane issues in the TODO? xD

**Comment by Tuhinshubhra** [comment]
Stick to winblows for now until we either fix the "MINOR" bug or frame it as a feature...

**Comment by TheBrokenWasp** [comment]
you fix it yet?

**Comment by TheBrokenWasp** [comment]
when is this going to be fixed?

**Comment by skylerbeyette** [comment]
@Souhardya please help me contact me on discord or skype                   relyks#0551      skype= relyks

**Comment by TheBrokenWasp** [comment]
hey skylerbeyette


get the fuck out of my post and make your own ffs

**Comment by TheBrokenWasp** [comment]
@Souhardya and @Tuhinshubhra how's the fix coming along?

**Comment by PhenomAmd** [comment]
> @Souhardya and @Tuhinshubhra how's the fix coming along?

calm your titties down people is CODING not copy/pasting like you btw im on debian and the error didnt got reproduced i installed with 7.0 and downgraded to 5.2 seems to work for me anyway ill need to check better

**Comment by Souhardya** [comment]
Hey there i am so sorry guys we will be catching along have my exams goin on

**Comment by PhenomAmd** [comment]
okay i replicated the issue it kinda only happens on linux servers im getting exactly the same issue 


`PHP Warning:  require(/var/www/html/private/helpers/authverify.php): failed to open stream: No such file or directory in /var/www/html/vendor/controller.php on line 66`

this is line 66
`require(APP_DIR .'helpers/'. strtolower($name) .'.php');`

and this is how my public_html directory looks 
![public_html](https://user-images.githubusercontent.com/43511497/46053954-29316b00-c102-11e8-8395-9f627815c0ce.png)

**Comment by PhenomAmd** [comment]
okay so i have finally figured out why this isnt working properly the panel has been developed in laravel i guess since laravel generates thoose 2 folders "private" and "vendor" i have tried installing it on my ubuntu server and its working just as its suppossed to, theres plenty of tutorials of how to install laravel on google you might find theese usefull (threadstarter) https://www.rosehosting.com/blog/install-laravel-on-ubuntu-16-04/ dunno which linux version you are using

**Comment by TheBrokenWasp** [comment]
ok, how do I do that on centos 7 @PhenomAmd?

**Comment by tehseensagar** [comment]
I encounter same issue , its a bug tried every thing even laravel but yet did no work. I've tried it on latest xampp php version 7.x and downloaded composer to install laravel , yet no change at all. I guess there is something missing in steps.

Regards

**Comment by PhenomAmd** [comment]
@TheBrokenWasp maybe try yum install laravel or yum install composer

i dont really know i got it from repositories im running on ubuntu xenial

@tehseensagar i have been looking on github all over the way seems like this panel is stripped directly from booh http botnet wich is totally compatible panel however it doesnt has malicious modules however it has a downloader built in anyway if we are seeing this github and looking for source code it might be because we have at least some coding skills so it wont be difficult for you to strip the modules out and get them to work omn booh botnet btw i should say that both sources (uboat and booh) are using almost same apis so you can expect high detection rate i would advice you to go with low level function, delayed execution

**Comment by tehseensagar** [comment]
> @TheBrokenWasp @eterna2000
> Please kindly look at this ? -> https://streamable.com/rgx73

This url is not showing any thing , there is certain configuration which should be set on xampp to get it doen like 

in php.ini

Add following settings:
----------------------------
max_execution_time = 5000
max_input_time = 5000
memory_limit = 1000M
post_max_size = 750M
upload_max_filesize = 750M

save it and now you will be able to import uboat.sql file.

so there are some other settings as well which support to be mention to fix this issue. I've been trying to get it work. If any one has done it in xampp so please share the steps or solution.

Regards

**Comment by AraFurieux** [comment]
Hello ! sorry the capcha doesn't load ? how do please ?

**Comment by AraFurieux** [comment]
Thanks !

**Comment by AraFurieux** [comment]
![capture_du_2018-10-17_19-02-46](https://user-images.githubusercontent.com/42409531/47103492-9c308c00-d23f-11e8-937d-2f63cf91aafe.png)
[

**Comment by tehseensagar** [comment]
how do I configure it on linux please help. share the step by step

Regards

**Comment by PhenomAmd** [comment]
@teehsengar the problem is not uploading the database the problem comes when you try to open the index ... With or without this settings i have replicated the issue however if it worked for you without problems its good.

I can not provide a step by step guide because first i dont know the commands  for every single distro i mean i know in centos you use yum in debian and ubuntu you use apt so i dont know you might try to search "how to instal composer and laravel and your distro"

**Comment by tehseensagar** [comment]
I've installed larava successfully on ubuntu. but still haivng issues. 

Followed the following guide/

https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/

**Comment by PhenomAmd** [comment]
but you have got the panel to work right?

**Comment by PhenomAmd** [comment]
> how do I configure it on linux please help. share the step by step
> 
> Regards

i think you are still missing composer aswell try to install it to

**Comment by tehseensagar** [comment]
composer is installed thats why its executed and created sub folder into /var/www/html/my-project

**Comment by PhenomAmd** [comment]
> composer is installed thats why its executed and created sub folder into /var/www/html/my-project
> 
> Ive created a virtualconfig file into apache and in that config I set serername localhost and root path to /var/www/html/my-project/

yeah indeed that was the method to get it to work seems like this panel is stripped from booh botnet the only differences i see in the code the "polymorphic builder" and the keylogger module however its exactly the same both botnets even trigger same detections on many AV because of the apis @Souhardya  not saying you copied pasted or whatever (that pisses us a lot ... i mean coders) but i see so many similitudes on both sources even on panel sources

**Comment by tehseensagar** [comment]
I will try it again. once it get back home.

share me your email / skype @PhenomAmd

**Comment by TheBrokenWasp** [comment]
For me installing laravel doesn't work, I have tried 6 different fucking methods now... on CentOS 7 btw

**Comment by PhenomAmd** [comment]
@TheBrokenWasp you need laravel aslong as composer in the past when i used centos for other purposes i have noticed that centos has less compatibility with many things dont know it this is the case you should try maybe another distro such as debian or ubuntu please be adviced that i dont know or use any other distros so no chance to actually know whats wrong on youre server btw im only trying to help not meaning i will solve your problem if you have any problem you could post here i will do my best to help you however im not the developer so dont expect too much from me

**Comment by tehseensagar** [comment]
@PhenomAmd  you can share FB .

**Comment by PhenomAmd** [comment]
ELExTr0
________________________________
De: tehseensagar <notifications@github.com>
Enviado: viernes, 26 de octubre de 2018 05:31 a. m.
Para: Souhardya/UBoat
CC: PhenomAmd; Mention
Asunto: Re: [Souhardya/UBoat] How to set up (#10)


@PhenomAmd<https://github.com/PhenomAmd> you can share FB .

**Comment by TheBrokenWasp** [comment]
@PhenomAmd I can't switch, I was trying on a VPS I own, it wasn't and isn't so important I just thought this looked cool and wanted to try it, but it doesn't really seem like an important project since this bug still exists and no updates have been released for months so yeah I'm just going to close this now, you guys can re-open it if you want but I don't see the point since you guys are never going to fix it... (btw I know you're not the creator I just don't know how to structure my sentences lol)

**Comment by van7hu** [comment]
> I encounter same issue , its a bug tried every thing even laravel but yet did no work. I've tried it on latest xampp php version 7.x and downloaded composer to install laravel , yet no change at all. I guess there is something missing in steps.
> 
> Found following errors in apache error.log file
> 
> `[Sun Oct 07 17:42:30.709656 2018] [php7:error] [pid 10488:tid 1664] [client ::1:50073] PHP Fatal error: Uncaught Error: Call to a member function render() on null in C:\\xampp\\htdocs\\PHP\\vendor\\controller.php:34\nStack trace:\n#0 C:\\xampp\\htdocs\\PHP\\vendor\\controller.php(8): Controller->beforeRequest()\n#1 C:\\xampp\\htdocs\\PHP\\vendor\\goat.php(89): Controller->__construct()\n#2 C:\\xampp\\htdocs\\PHP\\index.php(22): goat->__construct(Array)\n#3 {main}\n thrown in C:\\xampp\\htdocs\\PHP\\vendor\\controller.php on line 34`
> 
> Regards

Hi, I have the same problem.

**Comment by Developerworkerforpublic3310** [comment]
![capture](https://user-images.githubusercontent.com/48305600/53938788-27b59700-40d3-11e9-94ec-66200cadceb0.PNG)

I try every process but not worked .Object not found! this error will come , I think i don't have the one file with the name of .htaccess how i will get this file and what code should be in this file pleas help me out with this.

**Comment by Developerworkerforpublic3310** [comment]
![capture](https://user-images.githubusercontent.com/48305600/53948845-8d614d80-40ea-11e9-8080-519ecd55ebcd.PNG)
same error here
