### ISSUE TITLE
this problems from different VS versions?

### ISSUE THREAD

**Issue by eterna2000** [Souhardya/UBoat#11]
i have VS 2012

1>------ Build started: Project: boat, Configuration: Debug Win32 ------
1>Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>  xor.cpp
1>  WebsiteChecker.cpp
1>  WebSafeEncryption.cpp
1>  URLEncoding.cpp
1>  StringOperations.cpp
1>  Startup.cpp
1>  Sockets.cpp
1>  SocketInit.cpp
1>  Screenshot.cpp
1>c:\users\root\desktop\uboat-master\boat\screenshot.cpp(71): warning C4101: 'dwTotal' : unreferenced local variable
1>c:\users\root\desktop\uboat-master\boat\screenshot.cpp(76): warning C4101: 'dwTmp' : unreferenced local variable
1>c:\users\root\desktop\uboat-master\boat\screenshot.cpp(74): warning C4101: 'hp' : unreferenced local variable
1>  Processes.cpp
1>c:\users\root\desktop\uboat-master\boat\processes.cpp(45): warning C4800: 'BOOL' : forcing value to bool 'true' or 'false' (performance warning)
1>  PEIsAdmin.cpp
1>c:\users\root\desktop\uboat-master\boat\peisadmin.cpp(14): warning C4800: 'DWORD' : forcing value to bool 'true' or 'false' (performance warning)
1>  OSVersionChecker.cpp
1>  OSNetVersionChecker.cpp
1>c:\users\root\desktop\uboat-master\boat\osnetversionchecker.cpp(5): warning C4081: expected 'newline'; found ';'
1>c:\users\root\desktop\uboat-master\boat\osnetversionchecker.cpp(25): warning C4101: 'i' : unreferenced local variable
1>c:\users\root\desktop\uboat-master\boat\osnetversionchecker.cpp(27): warning C4101: 'achValue' : unreferenced local variable
1>  OSHwidChecker.cpp
1>c:\users\root\desktop\uboat-master\boat\oshwidchecker.cpp(1): warning C4005: '_CRT_SECURE_NO_WARNINGS' : macro redefinition
1>          command-line arguments :  see previous definition of '_CRT_SECURE_NO_WARNINGS'
1>  OSGpuChecker.cpp
1>c:\users\root\desktop\uboat-master\boat\osgpuchecker.cpp(1): warning C4005: '_CRT_SECURE_NO_WARNINGS' : macro redefinition
1>          command-line arguments :  see previous definition of '_CRT_SECURE_NO_WARNINGS'
1>  OSGetRam.cpp
1>c:\users\root\desktop\uboat-master\boat\osgetram.cpp(1): warning C4005: '_CRT_SECURE_NO_WARNINGS' : macro redefinition
1>          command-line arguments :  see previous definition of '_CRT_SECURE_NO_WARNINGS'
1>c:\users\root\desktop\uboat-master\boat\osgetram.cpp(11): warning C4244: 'argument' : conversion from 'unsigned __int64' to 'int', possible loss of data
1>  OSCpuChecker.cpp
1>c:\users\root\desktop\uboat-master\boat\oscpuchecker.cpp(1): warning C4005: '_CRT_SECURE_NO_WARNINGS' : macro redefinition
1>          command-line arguments :  see previous definition of '_CRT_SECURE_NO_WARNINGS'
1>  main.cpp
1>c:\users\root\desktop\uboat-master\boat\main.cpp(334): error C2143: syntax error : missing ';' before '{'
1>c:\users\root\desktop\uboat-master\boat\main.cpp(334): error C2143: syntax error : missing ';' before '}'
1>  Keylogger.cpp
1>c:\users\root\desktop\uboat-master\boat\keylogger.cpp(135): warning C4800: 'BOOL' : forcing value to bool 'true' or 'false' (performance warning)
1>  HttpQuery.cpp
1>  Generating Code...
1>c:\users\root\desktop\uboat-master\boat\startup.cpp(139): warning C4715: 'CreateRegKey' : not all control paths return a value
1>  Compiling...
1>  GateHelper.cpp
1>  Flood.cpp
1>  DownloadExecute.cpp
1>c:\users\root\desktop\uboat-master\boat\downloadexecute.cpp(99): warning C4244: 'argument' : conversion from 'time_t' to 'unsigned int', possible loss of data
1>  Command.cpp
1>c:\users\root\desktop\uboat-master\boat\command.cpp(22): error C2143: syntax error : missing ';' before '{'
1>c:\users\root\desktop\uboat-master\boat\command.cpp(22): error C2143: syntax error : missing ';' before '}'
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Souhardya** [comment]
I tested it with both VS 13 - 15 works fine for me 
Try compiling as release build and run it

**Comment by marcoSdsu** [comment]
Can give link vs 13-15?

**Comment by Souhardya** [comment]
Also idk what's with the syntactical errors 
I will check tho

**Comment by Souhardya** [comment]
@marcoSdsu just Google it man 
I have only this right now 
visual studio 2015 - https://go.microsoft.com/fwlink/?LinkId=615434&clcid=0x409

**Comment by eterna2000** [comment]
hmm.. VS 15 works but VS 12 not ))
Closed .

**Comment by Souhardya** [comment]
Cool
