### ISSUE TITLE
EXE Freez need help

### ISSUE THREAD

**Issue by eterna2000** [Souhardya/UBoat#12]
freez at this time 
![g1 1](https://user-images.githubusercontent.com/42667733/44726157-a7c8c780-aac6-11e8-8ada-68ee7ad46882.PNG)
and when i debugg it shows this 
![g1 2](https://user-images.githubusercontent.com/42667733/44726168-b31bf300-aac6-11e8-8fce-70c3b3ecdd14.PNG)

if u know why please help me and last one gate.php everythin ok? it return ::1 
![g1 3](https://user-images.githubusercontent.com/42667733/44726182-bb742e00-aac6-11e8-9609-ddee339bb309.PNG)

**Comment by Souhardya** [comment]
Just compile the exe in release mode and check

**Comment by Souhardya** [comment]
Also make sure your url is set up perfectly

**Comment by eterna2000** [comment]
do it but crush again :x: 
maybe im wrong idk but i use localhost for my xampp
![12222](https://user-images.githubusercontent.com/42667733/44769774-3d129d00-ab55-11e8-934f-197a3aa4a972.png)

**Comment by Souhardya** [comment]
Release mode shouldn't crash i cant reproduce the crash :3

**Comment by Souhardya** [comment]
Compile it in release mode .. run the executable bare .. and give crash logs

**Comment by Souhardya** [comment]
i will check in depth tho fucked up indexing into the hextable part

**Comment by eterna2000** [comment]
if i change localhost with 127.0.0.1  bot  connect but only once end then offline

**Comment by Souhardya** [comment]
I see try refreshing

**Comment by eterna2000** [comment]
ye doing but no changes 
![capture](https://user-images.githubusercontent.com/42667733/44782287-3fd1ba00-ab76-11e8-9ee7-c3bd9be11003.PNG)

**Comment by Souhardya** [comment]
Url encode function seems a good to go function give me a lil bit time 
Possibly it would be a good to go if i change it to [nOutputLen + 1] so it would not generate a null ptr dereference however I suggest you to try changing 
[ nOutputLen ] to [nOutputLen + 1] I am not on my pc as of now

**Comment by eterna2000** [comment]
ok i try

**Comment by Souhardya** [comment]
Lemme know

**Comment by eterna2000** [comment]
i fix this but got new problem
 cannot  see log in panel 
![lasssss](https://user-images.githubusercontent.com/42667733/44847263-6eb56200-ac42-11e8-8f43-f950e53d7646.png)

**Comment by r3xq1** [comment]
@Souhardya, Download the library SDK in the project for the bot please
