### ISSUE TITLE
Default Login Issue?

### ISSUE THREAD

**Issue by Dontmindmes** [Souhardya/UBoat#14]
https://gyazo.com/5eb62cbb6a9f8ce1b4303a56fe48b07c

i havent changed the passwords to anything

im using 
Username: root
Password: root

and it gives me wrong username/password error

**Comment by Dontmindmes** [comment]
Also when i get the ability to login i get this error

"
Fatal error: Uncaught Error: Call to undefined function mcrypt_create_iv() in C:\xampp\htdocs\UBoat\private\models\user.php:26 Stack trace: #0 C:\xampp\htdocs\UBoat\private\models\user.php(18): user->csrf(1) #1 C:\xampp\htdocs\UBoat\private\controllers\login.php(31): user->actionAuth(Array) #2 C:\xampp\htdocs\UBoat\vendor\goat.php(90): Login->index() #3 C:\xampp\htdocs\UBoat\index.php(22): goat->__construct(Array) #4 {main} thrown in C:\xampp\htdocs\UBoat\private\models\user.php on line 26
"


(after changing passwrd)

**Comment by Dontmindmes** [comment]
also when i revisit the login page i get this

https://gyazo.com/a21a2d04ff07a19f02b2cb42cdee7801

**Comment by Souhardya** [comment]
Have you copied the generated hash from test.php ? and updated the sql table ?

**Comment by Dontmindmes** [comment]
Yes I have done that, j have replaced the password in SQL too

**Comment by Souhardya** [comment]
Php ver ?

**Comment by Dontmindmes** [comment]
PHP Version 7.2.1

**Comment by Dontmindmes** [comment]
here is the sql user page

https://gyazo.com/6daf74216dbdf3002d503f365d72689d

**Comment by Souhardya** [comment]
Roll back to php ver 7.0

**Comment by Dontmindmes** [comment]
How can I do that? On xampp
