### ISSUE TITLE
Not connecting to panel

### ISSUE THREAD

**Issue by Dontmindmes** [Souhardya/UBoat#17]
Iv compiled the stub as 32, and ran the file but it is not connecting to the panel i cant seem to figure out why it is not

Gate.h file
https://gyazo.com/d481a0dfe023a8df6f9988de526fc723

Compiled Files
https://gyazo.com/298b9f5d9846312abcac26b9dd3e7ce3

Yes i ran the .exe

**Comment by Souhardya** [comment]
Possibly have a closer look and monitor why it's crashing

**Comment by Dontmindmes** [comment]
I have, i could not find the reason why its crashing, everything looks fine, panel is up and running on php 7.0, i set the knock panel correctly as localhost and /Panel/gate.php and everything looks fine, i compiled on visual studio 2015 as 32bit and its not working, could you possibly try to generate me a build to localhost   /Panel/gate.php  so i can see if the error is from my build its self or something else is wrong?

**Comment by Souhardya** [comment]
Cool I will provide you one in few hours

**Comment by Dontmindmes** [comment]
Thank you, just postnit here so I can see it, thanks

**Comment by Dontmindmes** [comment]
Also just found out that the .exe makes no connections either :/ i dont know why

**Comment by Dontmindmes** [comment]
https://gyazo.com/2b47e96d343f746b83f931c52757e42c
