### ISSUE TITLE
Tasks not working

### ISSUE THREAD

**Issue by Dontmindmes** [Souhardya/UBoat#19]
https://gyazo.com/9dc81a09469f3b9f34f33c0d6f21a21a
https://gyazo.com/d7dc22cfb15a70af618ccc1baac7b45f

**Comment by Dontmindmes** [comment]
Also how come after i killed the proccess it still shows up as online? 34 minutes pass and it still shows as online

**Comment by Souhardya** [comment]
Try this build maybe ? https://www.sendspace.com/file/361dan 
This is practically like not reproducible here  everything works fine asf

**Comment by Dontmindmes** [comment]
ur build crashes instantly 
https://gyazo.com/f405b95de902275b59b4ea542a687325

**Comment by Dontmindmes** [comment]
I got my builds working but how come when i run a task it says 2 bots

https://gyazo.com/6ae79dea96ba175d30f4e460f0899016

**Comment by Dontmindmes** [comment]
also even tho stub works, and tasks work now when i kill the bot it still shows bot is online, why is that

**Comment by Developerworkerforpublic3310** [comment]
![capture](https://user-images.githubusercontent.com/48305600/53946781-4709ef80-40e6-11e9-8b37-48a25afb6106.PNG)
i have the issue with the panel install can some one help me with this
