### ISSUE TITLE
Error While Build boat

### ISSUE THREAD

**Issue by dmouse207** [Souhardya/UBoat#20]
1>------ Build started: Project: boat, Configuration: Debug x64 ------
1>Command.cpp
1>DownloadExecute.cpp
1>d:\tools\uboat\uboat-master\bot\boat\downloadexecute.cpp(97): warning C4244: 'argument': conversion from 'time_t' to 'unsigned int', possible loss of data
1>Flood.cpp
1>GateHelper.cpp
1>d:\tools\uboat\uboat-master\bot\boat\gatehelper.cpp(23): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>Keylogger.cpp
1>OSCpuChecker.cpp
1>d:\tools\uboat\uboat-master\bot\boat\oscpuchecker.cpp(10): error C3861: '__cpuid': identifier not found
1>d:\tools\uboat\uboat-master\bot\boat\oscpuchecker.cpp(17): error C3861: '__cpuid': identifier not found
1>d:\tools\uboat\uboat-master\bot\boat\oscpuchecker.cpp(42): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>OSGetRam.cpp
1>d:\tools\uboat\uboat-master\bot\boat\osgetram.cpp(10): warning C4244: 'argument': conversion from 'unsigned __int64' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\osgetram.cpp(10): error C4996: '_itoa': This function or variable may be unsafe. Consider using _itoa_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\stdlib.h(640): note: see declaration of '_itoa'
1>OSGpuChecker.cpp
1>d:\tools\uboat\uboat-master\bot\boat\osgpuchecker.cpp(46): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>d:\tools\uboat\uboat-master\bot\boat\osgpuchecker.cpp(48): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>OSHwidChecker.cpp
1>d:\tools\uboat\uboat-master\bot\boat\oshwidchecker.cpp(11): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>OSNetVersionChecker.cpp
1>d:\tools\uboat\uboat-master\bot\boat\osnetversionchecker.cpp(5): warning C4081: expected 'newline'; found ';'
1>d:\tools\uboat\uboat-master\bot\boat\osnetversionchecker.cpp(64): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>d:\tools\uboat\uboat-master\bot\boat\osnetversionchecker.cpp(27): warning C4101: 'achValue': unreferenced local variable
1>d:\tools\uboat\uboat-master\bot\boat\osnetversionchecker.cpp(25): warning C4101: 'i': unreferenced local variable
1>d:\tools\uboat\uboat-master\bot\boat\osnetversionchecker.cpp(85): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>OSVersionChecker.cpp
1>d:\tools\uboat\uboat-master\bot\boat\osversionchecker.cpp(19): error C4996: 'GetVersionExA': was declared deprecated
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\um\sysinfoapi.h(378): note: see declaration of 'GetVersionExA'
1>d:\tools\uboat\uboat-master\bot\boat\osversionchecker.cpp(187): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>PEIsAdmin.cpp
1>d:\tools\uboat\uboat-master\bot\boat\peisadmin.cpp(22): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>d:\tools\uboat\uboat-master\bot\boat\peisadmin.cpp(24): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\string.h(133): note: see declaration of 'strcpy'
1>Processes.cpp
1>Screenshot.cpp
1>d:\tools\uboat\uboat-master\bot\boat\screenshot.cpp(52): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>d:\tools\uboat\uboat-master\bot\boat\screenshot.cpp(76): warning C4101: 'dwTmp': unreferenced local variable
1>d:\tools\uboat\uboat-master\bot\boat\screenshot.cpp(74): warning C4101: 'hp': unreferenced local variable
1>d:\tools\uboat\uboat-master\bot\boat\screenshot.cpp(71): warning C4101: 'dwTotal': unreferenced local variable
1>d:\tools\uboat\uboat-master\bot\boat\screenshot.cpp(136): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>Startup.cpp
1>d:\tools\uboat\uboat-master\bot\boat\startup.cpp(161): warning C4311: 'type cast': pointer truncation from 'HMODULE' to 'DWORD'
1>d:\tools\uboat\uboat-master\bot\boat\startup.cpp(161): warning C4302: 'type cast': truncation from 'HMODULE' to 'DWORD'
1>d:\tools\uboat\uboat-master\bot\boat\startup.cpp(161): warning C4312: 'type cast': conversion from 'unsigned long' to 'PIMAGE_NT_HEADERS' of greater size
1>URLEncoding.cpp
1>d:\tools\uboat\uboat-master\bot\boat\urlencoding.cpp(27): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>WebSafeEncryption.cpp
1>WebsiteChecker.cpp
1>d:\tools\uboat\uboat-master\bot\boat\websitechecker.cpp(50): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\websitechecker.cpp(69): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
1>xor.cpp
1>HttpQuery.cpp
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(53): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(61): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(69): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(75): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(82): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(89): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(108): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(127): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(128): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(141): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(81): warning C4477: 'sprintf_s' : format string '%d' requires an argument of type 'int', but variadic argument 1 has type 'size_t'
1>d:\tools\uboat\uboat-master\bot\boat\httpquery.cpp(81): note: consider using '%zd' in the format string
1>Generating Code...
1>d:\tools\uboat\uboat-master\bot\boat\startup.cpp(139): warning C4715: 'CreateRegKey': not all control paths return a value
1>Compiling...
1>main.cpp
1>d:\tools\uboat\uboat-master\bot\boat\main.cpp(103): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\main.cpp(163): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\main.cpp(179): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\main.cpp(183): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>SocketInit.cpp
1>Sockets.cpp
1>StringOperations.cpp
1>d:\tools\uboat\uboat-master\bot\boat\stringoperations.cpp(5): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\stringoperations.cpp(6): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\stringoperations.cpp(32): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\stringoperations.cpp(47): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\stringoperations.cpp(75): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
1>d:\tools\uboat\uboat-master\bot\boat\stringoperations.cpp(82): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
1>Generating Code...
1>Done building project "boat.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Souhardya** [comment]
VS version ?

**Comment by Souhardya** [comment]
Also don't have time to look at the whole debug log as of now just try compiling as 'release' build implies warnings will be ignored
