### ISSUE TITLE
__cpuid identifier not found error during building 

### ISSUE THREAD

**Issue by cryptonic01** [Souhardya/UBoat#21]
I'm getting __cpuid identifier not found error during the building it gives this error I couldn't understand what is wrong with me.
I'm currently  using Visual Studio 2017 and I'm using the latest source of the UBoat.
 and here  is the error image. 
If anybody can help me I would appreciate.
![image](https://user-images.githubusercontent.com/37256165/45051183-31811380-b038-11e8-8290-aee9ef3f38d2.png)

**Comment by Souhardya** [comment]
Aaah try adding 
#include <intrin.h> in this file
