### ISSUE TITLE
PHP error logs

### ISSUE THREAD

**Issue by tempussy** [Souhardya/UBoat#26]
I have followed the wiki but I am unable to access the login page. I can go to panel2/ but only a grey blank page is displayed. When I go to www.domain.com/panel2/ an error log is generated in public_html.

```
PHP Warning:  require(/home/tempussy/public_html/panel2/private/helpers/authverify.php): failed to open stream: No such file or directory in /home/tempussy/public_html/panel2/vendor/controller.php on line 66`
PHP Fatal error:  require(): Failed opening required '/home/tempussy/public_html/panel2/private/helpers/authverify.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/tempussy/public_html/panel2/vendor/controller.php on line 66
```

If I rename 'AuthVerify.php' to 'authverify.php' new errors are generated
```
PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/tempussy/public_html/panel2/vendor/goat.php:11) in /home/tempussy/public_html/panel2/vendor/controller.php on line 72
PHP Fatal error:  Uncaught Error: Call to a member function render() on null in /home/tempussy/public_html/panel2/vendor/controller.php:34
Stack trace:
#0 /home/tempussy/public_html/panel2/vendor/controller.php(8): Controller->beforeRequest()
#1 /home/tempussy/public_html/panel2/vendor/goat.php(89): Controller->__construct()
#2 /home/tempussy/public_html/panel2/index.php(22): goat->__construct(Array)
#3 {main}
  thrown in /home/noccogll/public_html/panel2/vendor/controller.php on line 34
```
My db settings in config.php are correct. I am not too sure about my URL's though.
'base_url' => 'http://domain.com/panel2/'
'external_address' => 'domain.com', // 'domain_goes_here', localhost

**Comment by MrJohnSmith12** [comment]
setup must be done with Laravel - but I have the same problem.

**Comment by ominitric** [comment]
Hey please i have problem setting up the panel please:
When I visit the address it goes to error403

**Comment by ominitric** [comment]
Am using windows 10 with xampp

**Comment by ominitric** [comment]
I have edited the config.php with localhost/mypath/ and dB set correctly still the same thing it direct me to error403 object not found

**Comment by Developerworkerforpublic3310** [comment]
i have the same issue when i run this project with Laravel framework this error will come "http://localhost/PHP/error/error403". Help me out with this if any one can

**Comment by Developerworkerforpublic3310** [comment]
![capture](https://user-images.githubusercontent.com/48305600/53947434-8c7aec80-40e7-11e9-8d32-46e69a90e834.PNG)
i am getting still this error , i try every solution to solve this but din't work, can some one help me with this?

**Comment by 62019** [comment]
same

**Comment by matricali** [comment]
> same

Hi @62019, we are currently working on the panel over this fork: github.com/matricali/UBoat-Panel
Can you test against it and give us feedback?
Thanks in advance.
