### ISSUE TITLE
Panel leading to error403 object not found

### ISSUE THREAD

**Issue by ominitric** [Souhardya/UBoat#27]
I have set the config.php correctly but visiting the localhost/bot leads to error403 page which doesn’t exist and also localhost/bot/login leads to error404 
Am running on windows 10 there is no folder named PHP in the file list downloaded is there any other link?

**Comment by jim-king098** [comment]
Download the bot.zip and panel.zip from [here](https://github.com/Souhardya/UBoat/releases).
Somehow the latest commit is quite problematic.

**Comment by ominitric** [comment]
I’ve been able get the login interface but I got captcha errors. Please help

**Comment by Developerworkerforpublic3310** [comment]
![capture](https://user-images.githubusercontent.com/48305600/53945770-26409a80-40e4-11e9-99e6-a418a5ad380a.PNG)
i have this error

**Comment by Developerworkerforpublic3310** [comment]
![capture](https://user-images.githubusercontent.com/48305600/53946527-d06cf200-40e5-11e9-9cb4-c0cfa9edd335.PNG)
still have same error, can some one help me here
