### ISSUE TITLE
help, capcha not show

### ISSUE THREAD

**Issue by gali313** [Souhardya/UBoat#3]
all instructions are already done, but when will login capcha does not appear.
what's wrong? can you help me dude.

![screenshot_165](https://user-images.githubusercontent.com/31598764/43681523-1a22a674-9880-11e8-8728-ec852fd2b334.png)

**Comment by H4xl0r** [comment]
Wrong php version ?

**Comment by gali313** [comment]
my panel using PHP/7.0.27 is this correct version or not dude?
thanks for answer.

![screenshot_173](https://user-images.githubusercontent.com/31598764/43737298-101355ae-99eb-11e8-81eb-643bc51624b5.png)

![screenshot_174](https://user-images.githubusercontent.com/31598764/43737311-19ba7948-99eb-11e8-820b-49027fd0593d.png)

**Comment by H4xl0r** [comment]
hm strange ... ok maybe give php 7.0.0 a try and please post the php modules enabled as well as the nginx settings 

maybe u need to enable some extensions (mod_rewrite etc ,,,)

**Comment by H4xl0r** [comment]
if not go for this :-)
https://github.com/zettabithf/LiteHTTP

**Comment by Souhardya** [comment]
PHP version i tested was 7.0.30 fyi

**Comment by AraFurieux** [comment]
I have thhis problem too ... I have xampp 7.0.32...

**Comment by AraFurieux** [comment]
Fatal error: Cannot declare class Error, because the name is already in use in /opt/lampp/htdocs/PHP/private/controllers/error.php on line 21 when i will see the image
