### ISSUE TITLE
Wrong Panel Repo link

### ISSUE THREAD

**Issue by DanusMinimus** [Souhardya/UBoat#46]
Hello gents, it seems that on your main repo(https://github.com/Souhardya/UBoat) you are sending users to download the panel from a wrong repo(https://github.com/matricali/UBoat-Panel/tree/3d038020f3e52f53160e0d6d1d979424aef53c8a) while you should be sending them to (https://github.com/matricali/UBoat-Panel).

I've located this issue by looking at https://github.com/Souhardya/UBoat/issues/26.

**Comment by matricali** [comment]
@DanusMinimus Hi! Thanks for taking the time to help up to improve the project

Can you bring us feedback regarding the latest version of the panel?
Thanks in advance!

Regards,
Jorge

**Comment by DanusMinimus** [comment]
I have tried setting it up by myself and with docker and it failed every time. I gave up eventually, there should be a more defined tutorial to the panel. Perhaps on setting up the WAMP environment correctly for the panel. I've tried using Docker to set it up quickly but that also didn't work.

**Comment by matricali** [comment]
@DanusMinimus can we get in touch?

**Comment by DanusMinimus** [comment]
Yes of curse, you can email me your preferred way of communication.
Danusminimus@outlook.com
