### ISSUE TITLE
SQL file to big

### ISSUE THREAD

**Issue by BetaIRL** [Souhardya/UBoat#48]
when i try to upload the sql file this happend

An oversized file may have been uploaded. Please read the documentation to solve this problem.

Please help

**Comment by matricali** [comment]
Hi!

**Comment by matricali** [comment]
Hi! @BetaIRL, you need to increase `upload_max_filesize` and `post_max_size` in your PHP installation.

https://www.php.net/manual/en/ini.core.php#ini.post-max-size
https://www.php.net/manual/en/ini.core.php#ini.upload-max-filesize
