### ISSUE TITLE
SSL Support?

### ISSUE THREAD

**Issue by ahmedm** [Souhardya/UBoat#5]
Am I wrong or the C&C communication is XOR'd over plain HTTP
I'm sorry but there is nothing Encrypted here

**Comment by H4xl0r** [comment]
feel free to send a pull request ....
not that hard to change it to https eg ssl

**Comment by ahmedm** [comment]
It's not just the web server part :) not that easy
The native plain socket needs to be wrapped in a secure SSL layer using a library like OpenSSL 
I'm sorry If I was a little rude in my first comment

**Comment by Souhardya** [comment]
Well I take criticism well and I will keep this is mind for further updates 
Thanks a lot :)
