### ISSUE TITLE
[Feature] server API to plug other bots 

### ISSUE THREAD

**Issue by khast3x** [Souhardya/UBoat#7]
Hey there, 
Thank you for the release :wink:  

It would be great if the admin panel had an API service so we could easily plug other bots to the UI.  
Regards,

**Comment by Souhardya** [comment]
Thanks for the suggestion m8 will think on it in the meanwhile people can contribute maybe ?

**Comment by khast3x** [comment]
Looking through the panel code. Would it possible for it to be tracked on git like the boat instead of a `zip` file?  
  
 That way we can fork the panel and contribute easily. Or maybe I missed it? If thats the case sorry :sweat_smile:

**Comment by Souhardya** [comment]
Too many files ;-;

**Comment by Tuhinshubhra** [comment]
@khast3x the panel is up you can now contribute here: https://github.com/Tuhinshubhra/UBoat-Panel

**Comment by khast3x** [comment]
Nice one thanks o/
